import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders

email_send = "dhanrajdeeru@gmail.com"
email_user = 'Athrvservices@gmail.com'    #fromm mail id
email_password = 'password'                   #from: mail password        
subject = 'Performance Report'
msg = MIMEMultipart()
msg['From'] = email_user
msg['To'] = email_send
msg['Subject'] = subject
        
body = ("""Greetings of the day,

        Your monthly performance report is hereby attached along with this email.
        Review it for self evaluation, and Improve your performance.

        Report generated by Artificial Intelligence Team

        Have a great day!""")
msg.attach(MIMEText(body,'plain'))
attachment = open(filename, "rb")
part = MIMEBase('application','octet-stream')
part.set_payload((attachment).read())
encoders.encode_base64(part)
part.add_header('Content-Disposition',"attachment; filename= "+filename)
msg.attach(part)
text = msg.as_string()
server = smtplib.SMTP('smtp.gmail.com',587)
server.starttls()
server.login(email_user,email_password)
server.sendmail(email_user,email_send,text)
server.quit()
        